serial:
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyUSB0
  timeout: {}
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1513605600
      _important:
        read_until: 1509547500
      _octopi:
        read_until: 1499253000
      _plugins:
        read_until: 1516579200
      _releases:
        read_until: 1513079100
    enabled_channels:
    - _octopi
    - _plugins
    - _important
    - _blog
  cura:
    cura_engine: /usr/bin/CuraEngine
    debug_logging: false
    default_profile: null
  pluginmanager:
    pip: /usr/bin/pip-sudo
    pip_force_user: true
  softwareupdate:
    pip_command: /usr/bin/pip-sudo
    _config_version: 6
    checks:
      octoprint:
        checkout_folder: null
        prerelease: false
        prerelease_channel: null
    notify_users: false
webcam:
  bitrate: 15000k
  ffmpeg: /usr/bin/ffmpeg
  ffmpegThreads: 0
  snapshot: http://localhost:8080/?action=snapshot
  stream: /webcam/?action=stream
  timelapse:
    fps: 25
    options:
      capturePostRoll: false
      interval: 20
    postRoll: 1
    type: timed
server:
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  commands:
    serverRestartCommand: sudo systemctl restart octoprint
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
system:
  actions: []
