serial:
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyUSB0
  timeout: {}
plugins:
  cura:
    cura_engine: /usr/bin/CuraEngine
    debug_logging: false
    default_profile: null
  pluginmanager:
    pip: /usr/bin/pip-sudo
webcam:
  ffmpeg: /usr/bin/ffmpeg
  ffmpegThreads: 4
  snapshot: /webcam/?action=snapshot
  stream: http://localhost/webcam/?action=stream
  timelapse:
    fps: 25
    options:
      interval: 10
    postRoll: 2
    type: timed
system:
  actions:
  - action: shutdown
    async: true
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    ignore: true
    name: Shutdown
  - action: reboot
    async: true
    command: sudo shutdown -r now
    confirm: You are about to reboot the system
    ignore: true
    name: Reboot
  - action: restart
    async: true
    command: sudo systemctl restart octoprint
    confirm: You are about to restart OctoPrint
    ignore: true
    name: Restart OctoPrint
